steps:
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    curl -sL https://github.com/gohugoio/hugo/releases/download/v0.95.0/hugo_0.95.0_Linux-64bit.tar.gz | tar -zxv
    ./hugo
    ./hugo -D
    ./hugo deploy

options:
 logging: CLOUD_LOGGING_ONLY
